### PR TITLE
High fives involve hands, not feet

### LINKED ISSUE #2: High fives do not involve feet

### PR DESCRIPTION
**Pull request by dlew**
Resolves #2

### CODE REVIEW

**Comment by thedufer** [comment]
Basilica discussion (bottom-to-top for those unfamiliar with Ian's weird belief system):

image

**Comment by dlew** [comment]
Just so it's clear, this whole issue/PR is somewhat tongue-in-cheek. (Or is that hand-in-air?)

**Comment by ianthehenry** [comment]
@dlew This is clearly very serious.

**Comment by Romainpetit** [comment]
Thanks for pointing this out.

**Pull request closed without merging**
